name: Wild
main: SkyLightMCPE\Main
version: 0.2_beta
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: SkyLightMCPE
website: https://github.com/SkyLightMCPE
commands:
  wild:
    description: "Teleport's you to a random place"
permissions:
  wild.command:
    description: "Wild command permission"
    default: true
