name: Wild
main: SkyLightMCPE\Main
version: 0.2_beta
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
author: SkyLightMCPE
website: https://github.com/SkyLightMCPE
commands:
  wild:
  usage: /wild 
  description: Teleports you in a random place!
  
permissions:
  wild.command:
    default: true
    description: Permission to use /wild
